version: "3.3"

volumes:
  kong_data: {}

networks:
  kong-net:
    driver: bridge
    external: true

services:
  kong:
    build:
      context: ./
    networks:
      - kong-net
    volumes:
      - ./kong-declarative-config.yml:/tmp/kong-declarative-config.yml
      - ./kong/plugins/kong-example:/usr/local/lib/luarocks/rocks-5.1/kong-plugin-example/1.0.0-0/lua/kong/plugins/kong-example
      - ./kong/plugins/kong-example:/usr/local/share/lua/5.1/kong/plugins/kong-example
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /tmp/kong-declarative-config.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled, kong-example, request-termination
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8443:8443"
      - "8444:8444"

