_format_version: "1.1"

services:
  - name: orders-v1-post
    url: https://run.mocky.io/v3/e002349c-8c93-4022-913b-df9cb6960605
    routes:
      - name: message
        tags:
          - orders
        methods:
          - GET
        paths:
          - "/message"
        plugins:
          - name: kong-example
            config:
              name: ROTA
              number: 1
    plugins:
       - name: kong-example
         config:
           name: SERVICE
           number: 2
plugins:
  - name: kong-example
    config:
      name: GLOBAL
      number: 3
